### ISSUE TITLE
"CalledProcessError: returned non-zero exit status 1." when runing EnergyPlus from python

### ISSUE THREAD

**Issue by zhengzhuang3** [jamiebull1/eplus_worker#1]
Dear Jamiebull,
     An error is thrown when I ran EnergyPlus from python. ("CalledProcessError: returned non-zero exit status 1." )
     The strange thing is that it succeeds when I run idf file with no hvac system assigned.
      However, when I assign VRF hvac system to above idf file through IDF editor or through eppy, the error is always given when using idf.run(). ("CalledProcessError: returned non-zero exit status 1."

**Comment by zhengzhuang3** [comment]
And I checked that when I run the same idf files in EnergyPlus directly by clicking buttons, it succeeds. So strange!

**Comment by jamiebull1** [comment]
Closing as duplicate of https://github.com/santoshphilip/eppy/issues/215
